"""employee_user_id_nullable

Revision ID: 08b7264a1a2a
Revises: 5d50d2622976
Create Date: 2026-06-10 06:10:24.451687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b7264a1a2a'
down_revision: Union[str, Sequence[str], None] = '5d50d2622976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'user_id', nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'user_id', nullable=False)
    pass
    # ### end Alembic commands ###
