"""fix employee nullable fields and backfill is_active

Revision ID: 0d3a45240844
Revises: 5a4e132a12d1
Create Date: 2026-06-10 06:34:30.290895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3a45240844'
down_revision: Union[str, Sequence[str], None] = '5a4e132a12d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'user_id', nullable=True)
    op.alter_column('employees', 'email', nullable=True)
    op.execute("UPDATE applications SET is_active = TRUE WHERE is_active IS NULL")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
