"""Add company isolation to Jobs and visibility to Candidates

Revision ID: 15739b05f055
Revises: 24f5763f21a0
Create Date: 2026-01-21 22:16:21.813911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15739b05f055'
down_revision: Union[str, Sequence[str], None] = '24f5763f21a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'company_id')
    op.drop_column('candidates', 'is_visible')
    op.drop_column('candidates', 'is_active')
    # ### end Alembic commands ###
