"""add_experience_and_education_to_candidates

Revision ID: 24f5763f21a0
Revises: b6e074afeb8a
Create Date: 2025-11-17 20:20:14.093448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f5763f21a0'
down_revision: Union[str, Sequence[str], None] = 'b6e074afeb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('years_of_experience', sa.Float(), nullable=True))
    op.add_column('candidates', sa.Column('education_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'education_level')
    op.drop_column('candidates', 'years_of_experience')
    # ### end Alembic commands ###
