
"""add_is_active_to_job

Revision ID: 266ea21c45ad
Revises: 8e5fc2422056
Create Date: 2026-06-21 23:29:13.087908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266ea21c45ad'
down_revision: Union[str, Sequence[str], None] = '8e5fc2422056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_standard_requirements', 'is_emergent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'is_instructor',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_instructor',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('jobs', 'is_active')
    op.alter_column('job_standard_requirements', 'is_emergent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
