"""Add exp and edu requirements to Jobs

Revision ID: 4f7da6183a78
Revises: 15739b05f055
Create Date: 2026-01-21 22:40:41.999208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7da6183a78'
down_revision: Union[str, Sequence[str], None] = '15739b05f055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('min_years_experience', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('min_education_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'min_education_level')
    op.drop_column('jobs', 'min_years_experience')
    # ### end Alembic commands ###
