"""Add rich profile fields to Candidate

Revision ID: b588bb1fdc2c
Revises: 4f7da6183a78
Create Date: 2026-01-22 03:21:30.353794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b588bb1fdc2c'
down_revision: Union[str, Sequence[str], None] = '4f7da6183a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('cv_text', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('formations', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('certifications', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('experience_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'experience_detail')
    op.drop_column('candidates', 'certifications')
    op.drop_column('candidates', 'formations')
    op.drop_column('candidates', 'cv_text')
    op.drop_column('candidates', 'bio')
    # ### end Alembic commands ###
