"""init candidates table

Revision ID: b6e074afeb8a
Revises: 002
Create Date: 2025-07-15 17:58:38.091464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6e074afeb8a'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_index(op.f('ix_candidates_first_name'), 'candidates', ['first_name'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_last_name'), 'candidates', ['last_name'], unique=False)
    op.create_table('job_requirements',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    op.drop_table('skill_endorsements')
    op.drop_table('candidate_saved_jobs')
    op.drop_table('job_skills')
    op.drop_table('interviews')
    op.drop_table('notifications')
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('applications', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_foreign_key(None, 'applications', 'candidates', ['candidate_id'], ['id'])
    op.create_table(
        "candidate_skills",
        sa.Column("candidate_id", sa.Integer, primary_key=True),
        sa.Column("skill_id", sa.Integer, primary_key=True),
        sa.Column("level", sa.Integer),
        sa.Column("years_experience", sa.Float),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"]),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"]),
    )
    
    
    
    op.create_foreign_key(None, 'candidate_skills', 'candidates', ['candidate_id'], ['id'])
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.add_column('jobs', sa.Column('company', sa.String(), nullable=True))
    op.alter_column('jobs', 'recruiter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('jobs', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('jobs', 'salary_min',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('jobs', 'salary_max',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.drop_constraint(op.f('jobs_company_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'job_type')
    op.drop_column('jobs', 'company_id')
    op.drop_column('jobs', 'is_active')
    op.alter_column('recruiters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('recruiters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('recruiters', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_recruiters_id'), 'recruiters', ['id'], unique=False)
    op.add_column('skills', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('skills', sa.Column('level1_description', sa.Text(), nullable=True))
    op.add_column('skills', sa.Column('level2_description', sa.Text(), nullable=True))
    op.add_column('skills', sa.Column('level3_description', sa.Text(), nullable=True))
    op.add_column('skills', sa.Column('level4_description', sa.Text(), nullable=True))
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('skills_name_key'), 'skills', type_='unique')
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'is_active')
    op.drop_column('skills', 'created_at')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('skills', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('skills', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('skills', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.create_unique_constraint(op.f('skills_name_key'), 'skills', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('skills', 'level4_description')
    op.drop_column('skills', 'level3_description')
    op.drop_column('skills', 'level2_description')
    op.drop_column('skills', 'level1_description')
    op.drop_column('skills', 'description')
    op.drop_index(op.f('ix_recruiters_id'), table_name='recruiters')
    op.alter_column('recruiters', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('recruiters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('recruiters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('jobs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('job_type', postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='jobtype'), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('experience_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'CLOSED', name='jobstatus'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('jobs_company_id_fkey'), 'jobs', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('jobs', 'salary_max',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('jobs', 'salary_min',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('jobs', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('jobs', 'recruiter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('jobs', 'company')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'candidate_skills', type_='foreignkey')
    op.alter_column('candidate_skills', 'level',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='skilllevel'),
               nullable=False)
    op.drop_column('candidate_skills', 'years_experience')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.alter_column('applications', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('MATCH', 'APPLICATION', 'INTERVIEW', 'SYSTEM', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('interviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('PHONE', 'VIDEO', 'ONSITE', 'TECHNICAL', name='interviewtype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('SCHEDULED', 'COMPLETED', 'CANCELLED', name='interviewstatus'), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('interviews_application_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interviews_pkey'))
    )
    op.create_table('job_skills',
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('required_level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='skilllevel'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('job_skills_job_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('job_skills_skill_id_fkey')),
    sa.PrimaryKeyConstraint('job_id', 'skill_id', name=op.f('job_skills_pkey'))
    )
    op.create_table('candidate_saved_jobs',
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('candidate_saved_jobs_job_id_fkey')),
    sa.PrimaryKeyConstraint('candidate_id', 'job_id', name=op.f('candidate_saved_jobs_pkey'))
    )
    op.create_table('skill_endorsements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endorser_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endorsed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['endorser_id'], ['users.id'], name=op.f('skill_endorsements_endorser_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('skill_endorsements_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_endorsements_pkey'))
    )
    op.drop_table('job_requirements')
    op.drop_index(op.f('ix_candidates_last_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_first_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
