"""add_onboarding_fields

Revision ID: fc1920402399
Revises: 1bc03fb69c77
Create Date: 2026-06-06 02:13:07.227619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1920402399'
down_revision: Union[str, Sequence[str], None] = '1bc03fb69c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('location', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('remote_ok', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('links', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('projects', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('profile_completeness_score', sa.Float(), nullable=True))
    op.add_column('candidates', sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'onboarding_completed_at')
    op.drop_column('candidates', 'profile_completeness_score')
    op.drop_column('candidates', 'projects')
    op.drop_column('candidates', 'links')
    op.drop_column('candidates', 'photo_url')
    op.drop_column('candidates', 'remote_ok')
    op.drop_column('candidates', 'location')
    op.drop_column('candidates', 'job_title')
    # ### end Alembic commands ###
